name: Node.js CI workflow

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master ]

jobs:
  build_npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        node-version2: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code from $GITHUB_REF
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run-script nodev
    - run : ls -al && pwd
    - name: Store Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-files
        path: index.js          
        retention-days: 10
 
  build_docker:
    needs: build_npm
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-files
      - name: Docker action
        with:
          DOCKERHUB_USERNAME: adnank
        uses: ./.github/actions/
      # - name: Login to ECR
      #   id: ecr
      #   uses: elgohr/ecr-login-action@master
      #   with:
      #     access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     region: ${{ secrets.AWS_REGION }} 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          # context: .
          # file: Dockerfies/Dockerfile
          tags: user/app:latest
          push: false
